"GET / HTTP/1.1" 200 5959
"GET /docs/ HTTP/1.1" 200 272846
"GET /docs/schema.js HTTP/1.1" 200 25352
"POST /login/ HTTP/1.1" 200 176
Internal Server Error: /dataMining/regression/
Traceback (most recent call last):
  File "/home/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/V-ZoomIn/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/V-ZoomIn/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/V-ZoomIn/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/V-ZoomIn/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ZoomInDev/apps/data_mining/views.py", line 64, in create
    serializer.data['mth_power'], request.data['error_type'])
  File "/home/ZoomInDev/db_tools/dataMining.py", line 80, in regression
    X_train = X_train.sort_values(by='Year', ascending=True)
  File "/home/V-ZoomIn/lib/python3.6/site-packages/pandas/core/frame.py", line 4421, in sort_values
    stacklevel=stacklevel)
  File "/home/V-ZoomIn/lib/python3.6/site-packages/pandas/core/generic.py", line 1379, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'Year'
"POST /dataMining/regression/ HTTP/1.1" 500 17251
"POST /dataMining/regression/ HTTP/1.1" 400 58
